#include <Windows.h>
#include <windows.h>
#include <iostream>
#include <cmath>
#define _USE_MATH_DEFINES
#include <math.h>
#include <vector>
#include <stdio.h>
#include <cstdint>
#include <cstddef>
#include <string.h>
#include <string>
#include <TlHelp32.h>
#include <thread>
#include <cstdint>
#include <iostream>
